// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oaujzuedlxwantnkcsht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hdWp6dWVkbHh3YW50bmtjc2h0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1OTg2NTcsImV4cCI6MjA2MTE3NDY1N30.aZxPa9q3NhaZf7WbWdqbM7lX4Ez7KuZp04fKtHwEnTE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);